### ISSUE TITLE
Uses Python 2

### ISSUE THREAD

**Issue by quozl** [Aniket21mathur/sugar-datastore-python3#1]
Opened python-carquinyol_0.114~Aniket21mathur.0-1_amd64.deb in emacs for analysis;

* [x] depends on Python 2 packages _python-gi_, _python-dbus_, _python-xapian_, and _python-sugar3_ but should depend on Python 3 packages,

* [x] `/usr/bin/copy-from-journal`, `copy-to-journal`, and `datastore-service` invoke `/usr/bin/python` not `/usr/bin/python3`, so the service will execute using Python 2.

**Comment by Aniket21mathur** [comment]
> * `/usr/bin/copy-from-journal`, `copy-to-journal`, and `datastore-service` invoke `/usr/bin/python` not `/usr/bin/python3`, so the service will execute using Python 2.

@quozl  I looked into `sugar-datastore-0.114~Aniket21mathur.0/bin/`, there the files invoke `/usr/bin/python3`, any other step where changes are required?

**Comment by Aniket21mathur** [comment]
> > * `/usr/bin/copy-from-journal`, `copy-to-journal`, and `datastore-service` invoke `/usr/bin/python` not `/usr/bin/python3`, so the service will execute using Python 2.
> 
> @quozl I looked into `sugar-datastore-0.114~Aniket21mathur.0/bin/`, there the files invoke `/usr/bin/python3`, on which step should the changes be required to execute  using  Python 3?

**Comment by quozl** [comment]
@Aniket21mathur, that's interesting, but directory `sugar-datastore-0.114~Aniket21mathur.0` would not be used by someone installing the package.  Why is the directory present in the repository, and what does it represent?  Why is the contents of that directory different to the contents of the file `python-carquinyol_0.114~Aniket21mathur.0-1_amd64.deb`?

**Comment by Aniket21mathur** [comment]
Thanks. I will remove it once I build the correct packages.
I analyzed the problem while running `debuild -us -uc` following [this](https://github.com/sugarlabs/sugar/blob/master/docs/debian-packaging-example.md) guide.

It might be something related to `carquinyol` being build in `python3.6\site-packages\` instead of `dist-packages` as I am getting this warning on running `debuild -us -uc`.

```
W: python-carquinyol: python-module-in-wrong-location usr/lib/python3.6/site-packages/carquinyol/__init__.py usr/lib/python3/dist-packages/carquinyol/__init__.py
```

**Comment by quozl** [comment]
That guide is incomplete.  On the assumption that `sugar-datastore-0.114~Aniket21mathur.0` is yuor debian source package directory, the problem of (a) wrong package name, and (b) wrong version of Python ... is caused by not changing the `debian/control` and `debian/rules` files.  I've looked at them, but can't see anything you've changed.

**Comment by Aniket21mathur** [comment]
@quozl I have made some changes, please have a look.
Thanks!

**Comment by quozl** [comment]
Yes, fixed.
